In [2]:
import pandas as pd

In [3]:
train_df = pd.read_csv('../results/outputs/Splits Stress_level_dataset/stress_level_train_scaled.csv')
test_df = pd.read_csv('../results/outputs/Splits Stress_level_dataset/stress_level_test_scaled.csv')

In [13]:
train_df.shape

(880, 26)

In [4]:
test_df.shape

(220, 21)

In [5]:
train_df.head()

,anxiety_level,self_esteem,mental_health_history,depression,headache,blood_pressure,sleep_quality,breathing_problem,noise_level,living_conditions,...,basic_needs,academic_performance,study_load,teacher_student_relationship,future_career_concerns,social_support,peer_pressure,extracurricular_activities,bullying,target
0,0.314428,0.795832,1,-0.333345,-0.349524,-1.430923,-0.426886,-0.521307,-0.489063,-0.462047,...,0.147712,0.152196,-0.453969,0.239311,-0.416290,0.118375,0.187084,0.163779,-0.413484,1
1,1.282463,-0.771658,1,1.611905,1.081086,0.979053,-1.074576,1.625730,1.764213,-1.351767,...,-0.540048,-1.265078,1.067908,-0.479438,0.887394,-0.837312,1.594209,1.563055,1.549820,2
2,-1.621643,0.795832,0,-1.241128,-1.064830,-0.225935,1.516182,-1.236986,-1.240155,1.317391,...,0.835473,0.860833,-1.214908,0.958060,-1.068132,1.074062,-1.220041,-0.535859,-1.067918,0
3,0.637107,-0.883621,1,0.574438,1.081086,0.979053,-1.074576,1.625730,1.764213,-1.351767,...,-0.540048,-1.265078,1.828847,-1.198188,0.887394,-0.837312,1.594209,0.863417,1.549820,2
4,-0.653607,1.019759,0,-1.630178,-1.064830,-0.225935,0.868493,-0.521307,-0.489063,0.427672,...,0.835473,0.860833,-1.214908,0.958060,-1.068132,1.074062,-0.516479,-1.235497,-1.067918,0

In [6]:
test_df.head()

,anxiety_level,self_esteem,mental_health_history,depression,headache,blood_pressure,sleep_quality,breathing_problem,noise_level,living_conditions,...,basic_needs,academic_performance,study_load,teacher_student_relationship,future_career_concerns,social_support,peer_pressure,extracurricular_activities,bullying,target
0,-0.492268,1.243686,0,-1.500495,-1.064830,-0.225935,1.516182,-0.521307,-1.240155,0.427672,...,0.835473,1.569470,-0.453969,1.676809,-1.068132,1.074062,-0.516479,-0.535859,-1.067918,0
1,-0.653607,0.795832,0,-1.111445,-1.064830,-0.225935,1.516182,-1.236986,-0.489063,0.427672,...,1.523233,1.569470,-1.214908,0.958060,-1.068132,1.074062,-1.220041,-1.235497,-1.067918,0
2,0.637107,-0.435767,1,0.833805,1.796392,0.979053,-1.074576,1.625730,0.262029,-0.462047,...,-0.540048,-0.556441,1.828847,-0.479438,1.539236,-0.837312,1.594209,1.563055,1.549820,2
3,1.443803,-0.323804,1,1.741588,1.081086,0.979053,-1.074576,0.910051,1.013121,-0.462047,...,-0.540048,-1.265078,1.828847,-1.198188,0.887394,-0.837312,1.594209,1.563055,0.895385,2
4,-0.814946,-0.771658,0,1.482221,1.081086,0.979053,-1.074576,-1.236986,-1.991247,0.427672,...,-0.540048,-1.973715,0.306970,-0.479438,-1.068132,-0.837312,-0.516479,-1.935135,-1.067918,0

In [7]:
#New Features

#mental_health_score, physical_score, academic_score, social_score

In [8]:
mental_health_cols = ["anxiety_level", "self_esteem", "mental_health_history", "depression"]
physical_cols = ["headache", "blood_pressure", "sleep_quality", "breathing_problem"]
environment_cols = ["noise_level", "living_conditions", "safety", "basic_needs"]
academic_cols = ["academic_performance", "study_load", "teacher_student_relationship", "future_career_concerns"]
social_cols = ["social_support", "peer_pressure", "extracurricular_activities", "bullying"]

for name, cols in [("mental_health_score", mental_health_cols),
                    ("physical_score", physical_cols),
                    ("environment_score", environment_cols),
                    ("academic_score", academic_cols),
                    ("social_score", social_cols)]:
    train_df[name] = train_df[cols].mean(axis=1)
    test_df[name] = test_df[cols].mean(axis=1)

In [14]:
test_df.shape

(220, 26)

In [9]:
train_df.head()

,anxiety_level,self_esteem,mental_health_history,depression,headache,blood_pressure,sleep_quality,breathing_problem,noise_level,living_conditions,...,social_support,peer_pressure,extracurricular_activities,bullying,target,mental_health_score,physical_score,environment_score,academic_score,social_score
0,0.314428,0.795832,1,-0.333345,-0.349524,-1.430923,-0.426886,-0.521307,-0.489063,-0.462047,...,0.118375,0.187084,0.163779,-0.413484,1,0.444229,-0.682160,-0.330784,-0.119688,0.013938
1,1.282463,-0.771658,1,1.611905,1.081086,0.979053,-1.074576,1.625730,1.764213,-1.351767,...,-0.837312,1.594209,1.563055,1.549820,2,0.780678,0.652823,-0.339384,0.052696,0.967443
2,-1.621643,0.795832,0,-1.241128,-1.064830,-0.225935,1.516182,-1.236986,-1.240155,1.317391,...,1.074062,-1.220041,-0.535859,-1.067918,0,-0.516735,-0.252892,0.630892,-0.116037,-0.437439
3,0.637107,-0.883621,1,0.574438,1.081086,0.979053,-1.074576,1.625730,1.764213,-1.351767,...,-0.837312,1.594209,0.863417,1.549820,2,0.331981,0.652823,-0.339384,0.063244,0.792533
4,-0.653607,1.019759,0,-1.630178,-1.064830,-0.225935,0.868493,-0.521307,-0.489063,0.427672,...,1.074062,-0.516479,-1.235497,-1.067918,0,-0.316007,-0.235895,0.596235,-0.116037,-0.436458

In [10]:
test_df.head()

,anxiety_level,self_esteem,mental_health_history,depression,headache,blood_pressure,sleep_quality,breathing_problem,noise_level,living_conditions,...,social_support,peer_pressure,extracurricular_activities,bullying,target,mental_health_score,physical_score,environment_score,academic_score,social_score
0,-0.492268,1.243686,0,-1.500495,-1.064830,-0.225935,1.516182,-0.521307,-1.240155,0.427672,...,1.074062,-0.516479,-0.535859,-1.067918,0,-0.187269,-0.073972,0.408462,0.431044,-0.261548
1,-0.653607,0.795832,0,-1.111445,-1.064830,-0.225935,1.516182,-1.236986,-0.489063,0.427672,...,1.074062,-1.220041,-1.235497,-1.067918,0,-0.242305,-0.252892,0.768175,0.061123,-0.612349
2,0.637107,-0.435767,1,0.833805,1.796392,0.979053,-1.074576,1.625730,0.262029,-0.462047,...,-0.837312,1.594209,1.563055,1.549820,2,0.508786,0.831650,-0.492501,0.583051,0.967443
3,1.443803,-0.323804,1,1.741588,1.081086,0.979053,-1.074576,0.910051,1.013121,-0.462047,...,-0.837312,1.594209,1.563055,0.895385,2,0.965397,0.473904,-0.127178,0.063244,0.803834
4,-0.814946,-0.771658,0,1.482221,1.081086,0.979053,-1.074576,-1.236986,-1.991247,0.427672,...,-0.837312,-0.516479,-1.935135,-1.067918,0,-0.026096,-0.062856,-0.300741,-0.803579,-1.089211

In [11]:
train_df.to_csv("../results/outputs/Stress_level_dataset_featured/stress_level_train_featured.csv", index=False)

In [12]:
test_df.to_csv("../results/outputs/Stress_level_dataset_featured/stress_level_test_featured.csv", index=False)